# Versioning
version: 1.0.0.{build}

# Configuration
# NOTE: Structure of MSYS2 installation outlined in this comment:
# http://help.appveyor.com/discussions/suggestions/615-support-for-msys2#comment_37571757
environment:
  GOPATH: C:\projects\go
  PROJECT_PATH: C:\projects\go-keytar

  matrix:
  - GOROOT: C:\go-x86
    GOARCH: 386
    MINGWROOT: C:\msys64\mingw32
  - GOROOT: C:\go
    GOARCH: amd64
    MINGWROOT: C:\msys64\mingw64

# Set up clone path
clone_folder: C:\projects\src\github.com\havoc-io\go-keytar

# Run build (primarily just here to stop the default Visual Studio build, since
# go test will build anyway)
build_script:
  - set PATH=%GOROOT%\bin;%MINGWROOT%\bin;%PATH%
  - cd %PROJECT_PATH%
  - go get -t
  - go build

# Run tests
test_script:
  - set PATH=%GOROOT%\bin;%MINGWROOT%\bin;%PATH%
  - cd %PROJECT_PATH%
  - go test

# Send notifications
notifications:
  - provider: Email
    to:
      - jacob@havoc.io
